name: Deploy to GitHub Pages
on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install Dependencies
        working-directory: ./frontend
        run: |
          npm ci
          npm install -g @angular/cli
          npm install angular-cli-ghpages --save-dev

      - name: Debug Pre-Build
        working-directory: ./frontend
        run: pwd && ls -la

      - name: Build
        working-directory: ./frontend
        run: |
          ng build --configuration production-github

      - name: Debug Post-Build
        working-directory: ./frontend
        run: |
          echo "Current directory structure:"
          ls -R dist/
          echo "Attempting to copy files..."
          DIST_DIR=$(find dist -type d -name "browser" | head -n 1)
          if [ -n "$DIST_DIR" ]; then
            echo "Found browser directory at: $DIST_DIR"
            cp "$DIST_DIR/index.html" "$DIST_DIR/404.html"
            echo "Files in $DIST_DIR:"
            ls -la "$DIST_DIR"
          else
            echo "Browser directory not found!"
            echo "Contents of dist:"
            ls -R dist/
            exit 1
          fi

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: frontend/dist/wealthcare-portal/browser
          branch: gh-pages
          clean: true

      - name: Debug Post-Deploy
        run: |
          echo "Deployment complete. Checking gh-pages branch..."
          git checkout gh-pages
          ls -la
